// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwoDz17BYcIyHLR8eiua21XzFiK8EfvM',
    appId: '1:902406455052:web:8364b430fc5844c0b75329',
    messagingSenderId: '902406455052',
    projectId: 'books-akmar',
    authDomain: 'books-akmar.firebaseapp.com',
    storageBucket: 'books-akmar.firebasestorage.app',
    measurementId: 'G-GFQKNHREMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqN1XwiyPDlTAjVv6Yp4yQNXEY-ECPGiI',
    appId: '1:902406455052:android:fc1cb482eab7af9ab75329',
    messagingSenderId: '902406455052',
    projectId: 'books-akmar',
    storageBucket: 'books-akmar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoLgA20jrlMsD5uT_cUlTsk2k4HNF31H4',
    appId: '1:902406455052:ios:64a098b1d4ef371ab75329',
    messagingSenderId: '902406455052',
    projectId: 'books-akmar',
    storageBucket: 'books-akmar.firebasestorage.app',
    iosBundleId: 'com.example.bookAkmar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoLgA20jrlMsD5uT_cUlTsk2k4HNF31H4',
    appId: '1:902406455052:ios:64a098b1d4ef371ab75329',
    messagingSenderId: '902406455052',
    projectId: 'books-akmar',
    storageBucket: 'books-akmar.firebasestorage.app',
    iosBundleId: 'com.example.bookAkmar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUwoDz17BYcIyHLR8eiua21XzFiK8EfvM',
    appId: '1:902406455052:web:e66590ea6e516341b75329',
    messagingSenderId: '902406455052',
    projectId: 'books-akmar',
    authDomain: 'books-akmar.firebaseapp.com',
    storageBucket: 'books-akmar.firebasestorage.app',
    measurementId: 'G-7RF132SS53',
  );
}
